version: "2"
services:
  medicalservice:
    build: ./server
    links:
      - db
    ports:
      - "5000:5000"

  admin:
    build: ./admin
    links:
      - medicalservice
    
  client:
    build: ./client
    links:
      - medicalservice

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
